import csv
import sys
import pandas as pd
import re
import numpy as np
from joblib import Memory

memory = Memory("/tmp/", verbose=3)

nst_path = "resources/nst/swe030224NST.pron"

COLUMNS = [
    "orthography",
    "parts_of_speech",
    "morphology",
    "decomposition",
    "decomposition_pos",
    "source",
    "lang",
    "is_garbage",
    "domain",
    "is_acronym",
    "acronym_expansion",
    "trans_1",
    "trans_2",
    "trans_3",
    "trans_4",
    "trans_5",
    "trans_6",
    "trans_7",
    "trans_8",
    "trans_9",
    "trans_10",
    "trans_11",
    "trans_12",
    "trans_13",
    "trans_14",
    "trans_15",
    "trans_16",
    "trans_autogenerated",
    "set_id",
    "set_name",
    "stylistic_information",
    "inflector_role",
    "lemma",
    "inflection_rule",
    "morph_label",
    "compounder_code",
    "semantic_info",
    "disp_1",
    "disp_2",
    "disp_3",
    "disp_4",
    "disp_5",
    "disp_6",
    "disp_7",
    "disp_8",
    "disp_9",
    "frequency",
    "original_orthography",
    "comment_field",
    "update_info",
    "unique_id",
]


class _nst_dialect(csv.Dialect):
    """Describe the usual properties of Excel-generated CSV files."""

    delimiter = ";"
    doublequote = True
    skipinitialspace = False
    lineterminator = "\r\n"
    quoting = csv.QUOTE_NONE

@memory.cache
def load_lexicon(path):
    """
    Returns NST lexicon as pandas.DataFrame.
    """
    print("Reading NST lexicon from {}".format(path))
    df = pd.read_csv(
        path,
        encoding="utf-8",
        header=None,
        dialect=_nst_dialect,
        dtype={10: np.str_, 9: np.str_},
    )
    df.columns = COLUMNS
    df["orthography"] = df["orthography"].str.lower()
    return df.append(missing, sort=True).drop_duplicates(subset="orthography").set_index("orthography").sort_index()


missing = pd.DataFrame.from_dict({
    "på": ["på", "KN", "NaN", "på", "KN", "LEX", "SWE", "NaN", "NaN", "NaN", "NaN", "\"po:", "1", "STD", "SWE", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "spd_se", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "NaN", "på", "NaN", "NaN", "0000"]
}, orient="index", columns=COLUMNS)